name: Sync Changes to Bluebook
on: [push]
run-name: Syncing Latest Backup to Bluebook Pages
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bluebook Build
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: niemtec
          repo: bluebook
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          workflow_file_name: ci.yaml
          ref: main
          wait_interval: 5
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
